services:
  app:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}-app"
    volumes:
      - ./src:/var/www/html
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: "${PROJECT_NAME}-nginx"
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - internal

  redis:
    image: redis:alpine
    container_name: "${PROJECT_NAME}-redis"
    ports:
      - "6379:6379"
    networks:
      - internal

networks:
  internal:
    driver: bridge